!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 75
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 3.5, y: 0, z: 38.25}
      rotations: [270]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 1, y: 0, z: 38.25}
      - !Vector3 {x: 2, y: 0, z: 36.25}
      - !Vector3 {x: 4.5, y: 0, z: 37.25}
      - !Vector3 {x: 4.5, y: 0, z: 39.25}
      sizes:
      - !Vector3 {x: 2, y: 5, z: .5}
      - !Vector3 {x: 4, y: 5, z: .5}
      - !Vector3 {x: 1, y: 5, z: 1.5}
      - !Vector3 {x: 1, y: 5, z: 1.5}
      rotations: [0,0,0,0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 0.25, y: 0, z: 39.25}
      - !Vector3 {x: 0.25, y: 0, z: 37.25}
      - !Vector3 {x: 2.25, y: 0, z: 38.25}
      sizes:
      - !Vector3 {x: .5, y: 5, z: 1.5}
      - !Vector3 {x: .5, y: 5, z: 1.5}
      - !Vector3 {x: .5, y: 5, z: .5}  
      rotations: [0,0,0]
      colors:
      - !RGB {r: 255, g: 50, b: 50}
      - !RGB {r: 50, g: 50, b: 255}
      - !RGB {r: 255, g: 50, b: 50}
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 1.5, y: 0, z: 39.25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: BadGoal
      positions:
      - !Vector3 {x: 1.5, y: 0, z: 37.25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  1: !Arena
    pass_mark: 0
    t: 75
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 3.5, y: 0, z: 38.25}
      rotations: [270]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 1, y: 0, z: 38.25}
      - !Vector3 {x: 2, y: 0, z: 36.25}
      - !Vector3 {x: 4.5, y: 0, z: 37.25}
      - !Vector3 {x: 4.5, y: 0, z: 39.25}
      sizes:
      - !Vector3 {x: 2, y: 5, z: .5}
      - !Vector3 {x: 4, y: 5, z: .5}
      - !Vector3 {x: 1, y: 5, z: 1.5}
      - !Vector3 {x: 1, y: 5, z: 1.5}
      rotations: [0,0,0,0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 0.25, y: 0, z: 39.25}
      - !Vector3 {x: 0.25, y: 0, z: 37.25}
      - !Vector3 {x: 2.25, y: 0, z: 38.25}
      sizes:
      - !Vector3 {x: .5, y: 5, z: 1.5}
      - !Vector3 {x: .5, y: 5, z: 1.5}
      - !Vector3 {x: .5, y: 5, z: .5}  
      rotations: [0,0,0]
      colors:
      - !RGB {r: 255, g: 50, b: 50}
      - !RGB {r: 50, g: 50, b: 255}
      - !RGB {r: 255, g: 50, b: 50}
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 1.5, y: 0, z: 39.25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: BadGoal
      positions:
      - !Vector3 {x: 1.5, y: 0, z: 37.25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  2: !Arena
    pass_mark: 0
    t: 75
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 3.5, y: 0, z: 38.25}
      rotations: [270]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 1, y: 0, z: 38.25}
      - !Vector3 {x: 2, y: 0, z: 36.25}
      - !Vector3 {x: 4.5, y: 0, z: 37.25}
      - !Vector3 {x: 4.5, y: 0, z: 39.25}
      sizes:
      - !Vector3 {x: 2, y: 5, z: .5}
      - !Vector3 {x: 4, y: 5, z: .5}
      - !Vector3 {x: 1, y: 5, z: 1.5}
      - !Vector3 {x: 1, y: 5, z: 1.5}
      rotations: [0,0,0,0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 0.25, y: 0, z: 39.25}
      - !Vector3 {x: 0.25, y: 0, z: 37.25}
      - !Vector3 {x: 2.25, y: 0, z: 38.25}
      sizes:
      - !Vector3 {x: .5, y: 5, z: 1.5}
      - !Vector3 {x: .5, y: 5, z: 1.5}
      - !Vector3 {x: .5, y: 5, z: .5}  
      rotations: [0,0,0]
      colors:
      - !RGB {r: 255, g: 50, b: 50}
      - !RGB {r: 50, g: 50, b: 255}
      - !RGB {r: 50, g: 50, b: 255}
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 1.5, y: 0, z: 37.25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: BadGoal
      positions:
      - !Vector3 {x: 1.5, y: 0, z: 39.25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  3: !Arena
    pass_mark: 0
    t: 75
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 3.5, y: 0, z: 38.25}
      rotations: [270]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 1, y: 0, z: 38.25}
      - !Vector3 {x: 2, y: 0, z: 36.25}
      - !Vector3 {x: 4.5, y: 0, z: 37.25}
      - !Vector3 {x: 4.5, y: 0, z: 39.25}
      sizes:
      - !Vector3 {x: 2, y: 5, z: .5}
      - !Vector3 {x: 4, y: 5, z: .5}
      - !Vector3 {x: 1, y: 5, z: 1.5}
      - !Vector3 {x: 1, y: 5, z: 1.5}
      rotations: [0,0,0,0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 0.25, y: 0, z: 39.25}
      - !Vector3 {x: 0.25, y: 0, z: 37.25}
      - !Vector3 {x: 2.25, y: 0, z: 38.25}
      sizes:
      - !Vector3 {x: .5, y: 5, z: 1.5}
      - !Vector3 {x: .5, y: 5, z: 1.5}
      - !Vector3 {x: .5, y: 5, z: .5}  
      rotations: [0,0,0]
      colors:
      - !RGB {r: 255, g: 50, b: 50}
      - !RGB {r: 50, g: 50, b: 255}
      - !RGB {r: 50, g: 50, b: 255}
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 1.5, y: 0, z: 37.25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: BadGoal
      positions:
      - !Vector3 {x: 1.5, y: 0, z: 39.25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  4: !Arena
    pass_mark: 0
    t: 75
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 3.5, y: 0, z: 38.25}
      rotations: [270]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 1, y: 0, z: 38.25}
      - !Vector3 {x: 2, y: 0, z: 36.25}
      - !Vector3 {x: 4.5, y: 0, z: 37.25}
      - !Vector3 {x: 4.5, y: 0, z: 39.25}
      sizes:
      - !Vector3 {x: 2, y: 5, z: .5}
      - !Vector3 {x: 4, y: 5, z: .5}
      - !Vector3 {x: 1, y: 5, z: 1.5}
      - !Vector3 {x: 1, y: 5, z: 1.5}
      rotations: [0,0,0,0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 0.25, y: 0, z: 39.25}
      - !Vector3 {x: 0.25, y: 0, z: 37.25}
      - !Vector3 {x: 2.25, y: 0, z: 38.25}
      sizes:
      - !Vector3 {x: .5, y: 5, z: 1.5}
      - !Vector3 {x: .5, y: 5, z: 1.5}
      - !Vector3 {x: .5, y: 5, z: .5}  
      rotations: [0,0,0]
      colors:
      - !RGB {r: 50, g: 50, b: 255}
      - !RGB {r: 255, g: 50, b: 50}
      - !RGB {r: 255, g: 50, b: 50}
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 1.5, y: 0, z: 37.25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: BadGoal
      positions:
      - !Vector3 {x: 1.5, y: 0, z: 39.25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  5: !Arena
    pass_mark: 0
    t: 75
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 3.5, y: 0, z: 38.25}
      rotations: [270]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 1, y: 0, z: 38.25}
      - !Vector3 {x: 2, y: 0, z: 36.25}
      - !Vector3 {x: 4.5, y: 0, z: 37.25}
      - !Vector3 {x: 4.5, y: 0, z: 39.25}
      sizes:
      - !Vector3 {x: 2, y: 5, z: .5}
      - !Vector3 {x: 4, y: 5, z: .5}
      - !Vector3 {x: 1, y: 5, z: 1.5}
      - !Vector3 {x: 1, y: 5, z: 1.5}
      rotations: [0,0,0,0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 0.25, y: 0, z: 39.25}
      - !Vector3 {x: 0.25, y: 0, z: 37.25}
      - !Vector3 {x: 2.25, y: 0, z: 38.25}
      sizes:
      - !Vector3 {x: .5, y: 5, z: 1.5}
      - !Vector3 {x: .5, y: 5, z: 1.5}
      - !Vector3 {x: .5, y: 5, z: .5}  
      rotations: [0,0,0]
      colors:
      - !RGB {r: 50, g: 50, b: 255}
      - !RGB {r: 255, g: 50, b: 50}
      - !RGB {r: 255, g: 50, b: 50}
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 1.5, y: 0, z: 37.25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: BadGoal
      positions:
      - !Vector3 {x: 1.5, y: 0, z: 39.25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  6: !Arena
    pass_mark: 0
    t: 75
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 3.5, y: 0, z: 38.25}
      rotations: [270]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 1, y: 0, z: 38.25}
      - !Vector3 {x: 2, y: 0, z: 36.25}
      - !Vector3 {x: 4.5, y: 0, z: 37.25}
      - !Vector3 {x: 4.5, y: 0, z: 39.25}
      sizes:
      - !Vector3 {x: 2, y: 5, z: .5}
      - !Vector3 {x: 4, y: 5, z: .5}
      - !Vector3 {x: 1, y: 5, z: 1.5}
      - !Vector3 {x: 1, y: 5, z: 1.5}
      rotations: [0,0,0,0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 0.25, y: 0, z: 39.25}
      - !Vector3 {x: 0.25, y: 0, z: 37.25}
      - !Vector3 {x: 2.25, y: 0, z: 38.25}
      sizes:
      - !Vector3 {x: .5, y: 5, z: 1.5}
      - !Vector3 {x: .5, y: 5, z: 1.5}
      - !Vector3 {x: .5, y: 5, z: .5}  
      rotations: [0,0,0]
      colors:
      - !RGB {r: 50, g: 50, b: 255}
      - !RGB {r: 255, g: 50, b: 50}
      - !RGB {r: 50, g: 50, b: 255}
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 1.5, y: 0, z: 39.25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: BadGoal
      positions:
      - !Vector3 {x: 1.5, y: 0, z: 37.25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  7: !Arena
    pass_mark: 0
    t: 75
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 3.5, y: 0, z: 38.25}
      rotations: [270]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 1, y: 0, z: 38.25}
      - !Vector3 {x: 2, y: 0, z: 36.25}
      - !Vector3 {x: 4.5, y: 0, z: 37.25}
      - !Vector3 {x: 4.5, y: 0, z: 39.25}
      sizes:
      - !Vector3 {x: 2, y: 5, z: .5}
      - !Vector3 {x: 4, y: 5, z: .5}
      - !Vector3 {x: 1, y: 5, z: 1.5}
      - !Vector3 {x: 1, y: 5, z: 1.5}
      rotations: [0,0,0,0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 0.25, y: 0, z: 39.25}
      - !Vector3 {x: 0.25, y: 0, z: 37.25}
      - !Vector3 {x: 2.25, y: 0, z: 38.25}
      sizes:
      - !Vector3 {x: .5, y: 5, z: 1.5}
      - !Vector3 {x: .5, y: 5, z: 1.5}
      - !Vector3 {x: .5, y: 5, z: .5}  
      rotations: [0,0,0]
      colors:
      - !RGB {r: 50, g: 50, b: 255}
      - !RGB {r: 255, g: 50, b: 50}
      - !RGB {r: 50, g: 50, b: 255}
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 1.5, y: 0, z: 39.25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: BadGoal
      positions:
      - !Vector3 {x: 1.5, y: 0, z: 37.25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}