!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Agent
    - !Item
      name: GoodGoal
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 2.5, y: 0, z: 5}
      - !Vector3 {x: 37.5, y: 0, z: 35}
      rotations: [0, 0]
      sizes:
      - !Vector3 {x: 5, y: 10, z: 10}
      - !Vector3 {x: 5, y: 10, z: 10}
      colors: 
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
  1: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Agent
    - !Item
      name: GoodGoal
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 2.5, y: 0, z: 5}
      - !Vector3 {x: 37.5, y: 0, z: 35}
      rotations: [0, 0]
      sizes:
      - !Vector3 {x: 5, y: 10, z: 10}
      - !Vector3 {x: 5, y: 10, z: 10}
      colors: 
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
  2: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Agent
    - !Item
      name: GoodGoal
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 15, y: 0, z: 15}
      - !Vector3 {x: 15, y: 0, z: 25}
      - !Vector3 {x: 25, y: 0, z: 15}
      - !Vector3 {x: 25, y: 0, z: 25}
      rotations: [0, 0, 0, 0]
      sizes:
      - !Vector3 {x: 5, y: 10, z: 5}
      - !Vector3 {x: 5, y: 10, z: 5}
      - !Vector3 {x: 5, y: 10, z: 5}
      - !Vector3 {x: 5, y: 10, z: 5}
      colors: 
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
  3: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Agent
    - !Item
      name: GoodGoal
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 15, y: 0, z: 15}
      - !Vector3 {x: 15, y: 0, z: 25}
      - !Vector3 {x: 25, y: 0, z: 15}
      - !Vector3 {x: 25, y: 0, z: 25}
      rotations: [0, 0, 0, 0]
      sizes:
      - !Vector3 {x: 5, y: 10, z: 5}
      - !Vector3 {x: 5, y: 10, z: 5}
      - !Vector3 {x: 5, y: 10, z: 5}
      - !Vector3 {x: 5, y: 10, z: 5}
      colors: 
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
  4: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Agent
    - !Item
      name: GoodGoal
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 2.5, y: 0, z: 2.5}
      - !Vector3 {x: 10, y: 0, z: 10}
      - !Vector3 {x: 17.5, y: 0, z: 17.5}
      - !Vector3 {x: 22.5, y: 0, z: 22.5}
      - !Vector3 {x: 30, y: 0, z: 30}
      - !Vector3 {x: 37.5, y: 0, z: 37.5}
      rotations: [0, 0, 0, 0, 0, 0]
      sizes:
      - !Vector3 {x: 5, y: 10, z: 5}
      - !Vector3 {x: 5, y: 10, z: 5}
      - !Vector3 {x: 5, y: 10, z: 5}
      - !Vector3 {x: 5, y: 10, z: 5}
      - !Vector3 {x: 5, y: 10, z: 5}
      - !Vector3 {x: 5, y: 10, z: 5}
      colors: 
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
  5: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Agent
    - !Item
      name: GoodGoal
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 2.5, y: 0, z: 2.5}
      - !Vector3 {x: 10, y: 0, z: 10}
      - !Vector3 {x: 17.5, y: 0, z: 17.5}
      - !Vector3 {x: 22.5, y: 0, z: 22.5}
      - !Vector3 {x: 30, y: 0, z: 30}
      - !Vector3 {x: 37.5, y: 0, z: 37.5}
      rotations: [0, 0, 0, 0, 0, 0]
      sizes:
      - !Vector3 {x: 5, y: 10, z: 5}
      - !Vector3 {x: 5, y: 10, z: 5}
      - !Vector3 {x: 5, y: 10, z: 5}
      - !Vector3 {x: 5, y: 10, z: 5}
      - !Vector3 {x: 5, y: 10, z: 5}
      - !Vector3 {x: 5, y: 10, z: 5}
      colors: 
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
