wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/examples/gymwrapper.py
    python_version: 3.10.6
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690236684.363018
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 23
      - 35
      4: 3.10.6
      5: 0.15.5
      8:
      - 5
