!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Agent
      # rotations: [-1]
    - !Item
      name: GoodGoalBounce
      rotations: [-1]
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2} # Goal Size