!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 19}
      rotations: [0]
      sizes:
      - !Vector3 {x: 8, y: 3, z: 2}
      colors:
      - !RGB {r: 236, g: 195, b: 153} #color parameter
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 35}
      sizes:
      - !Vector3 {x: 4, y: 4, z: 4} # Goal Size
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: -1, y: 0, z: 8}
      rotations: [0]
